### PR TITLE
Initial work for meteor 1.2

### PR DESCRIPTION
**Pull request by fourseven**
Credit to @sebakerckhof - I'll test this tonight and roll a release if it's all good. The new build chain should mean that autoprefixer should become a separate thing, so it's not that much of a problem that it's removed here.

Ref #106

### CODE REVIEW

**Comment by sebakerckhof** [comment]
Best wait to merge until this issue is resolved: https://github.com/meteor/meteor/issues/5074

In some situations, we get in endless refresh loops. However, it also seems to happen with some other build plugins (e.g. jsx), so it might be either a meteor bug, or something these build plugins collectively do wrong.

**Comment by sebakerckhof** [comment]
Okay, the above mentioned issue was a meteor bug and is solved in the latest 1.2rc (rc.12)

The only problem I see remaining is the fact that node-sass returns source map filepaths not relative to the meteor directory. This means that currently you are required to always include the package from which you import (or {} if you are not inside a package). Even for imports within a package you would need to specify the package name for each import or decodeFilePath will fail.

**Comment by sebakerckhof** [comment]
Okay, I found a way to make imports work without having to specify the package.
Behavior is now consistent with the official less package.

I also removed the autoprefixer test.

There is currently no support for any options, but most of them might not make sense anymore or would be hard to integrate in the new build system.

**Comment by fourseven** [comment]
That's a good amount of refactoring/rewriting, thanks! I seem to remember that there's a way to set the minimum version of meteor needed for a package, but can't find the docs - that's the only thing missing and then I'll do a release

**Comment by sebakerckhof** [comment]
Hmm, I can only think of the versionsFrom method, but that's not really what you want.
I've written a [private package server](https://github.com/sebakerckhof/stratosphere) for meteor, and as far as I know, there is no field that gets published that really specifies the minimum meteor version.

However, the fact that it depends on isobuild:compiler-plugins, which will only be available if you are using the latest meteor tool, should be sufficient to make the package constraint solver throw an error if you try to use this package pre-1.2

**Comment by sebakerckhof** [comment]
I added some comments and one thing that was missing: allowing to import files without specifying their extension. AFAIK, this is now fully complete.

**Pull request merged**
